### PR TITLE
Support graphql version 1.8

### PR DESCRIPTION
**Pull request by CyborgMaster**
Specifically, this supports version 1.8.0.pre11

### CODE REVIEW

**Comment by CyborgMaster** [comment]
I fixed the conflicts with master

**Comment by fameoflight** [comment]
@etripier can we merge this?

**Comment by obrie** [comment]
For what it's worth, in the meantime I'm using the following patch until a new gem with class-based compatibility gets released:

```ruby
GraphQL::Preload::Instrument.class_eval do
  def instrument(_type, field)
    return field unless field.metadata.include?(:preload)

    old_resolver = field.resolve_proc
    new_resolver = ->(obj, args, ctx) do
      return old_resolver.call(obj, args, ctx) unless obj

      if field.metadata[:preload_scope]
        scope = field.metadata[:preload_scope].call(args, ctx)
      end

      # FIX: Change from `obj` to `obj.object`
      preload(obj.object, field.metadata[:preload], scope).then do
        old_resolver.call(obj, args, ctx)
      end
    end

    field.redefine do
      resolve(new_resolver)
    end
  end
end

module GraphQL
  module Preload
    module SchemaMethods
      def enable_preloading
        instrument(:field, GraphQL::Preload::Instrument.new)
      end
    end
  end
end

GraphQL::Schema.extend GraphQL::Preload::SchemaMethods
GraphQL::Schema::Field.accepts_definition :preload
GraphQL::Schema::Field.accepts_definition :preload_scope
```

**Comment by bbugh** [comment]
Any way we can help get this merged? This is the only thing holding us back from switching to the class-based setup. This gem is awesome and we need it!

**Comment by Envek** [comment]
@CyborgMaster, in https://github.com/Envek/graphql-preload/commit/61bca432a813f6f1288860ef19c8734dfd901ee7 I added `preload` and `preload_scope` methods to field class so preloads can be defined inside field definition's block:

```ruby
field :somethings, [Type] do
  preload :other_things
  preload_scope ->(*) { OtherThing.order(foo: :asc) }
end
```

Could you please add it to your PR? (it is fast-forwardable)

@etripier, your gem is awesome and I want it to work with graphql gem v1.8.x. Could you please review it?

**Comment by CyborgMaster** [comment]
@Envek the move to 1.8 was designed to move away from the definition blocks towards parameters.  I'm not sure if your change is the direction the the main GraphQL gem is going.  What do you think?

**Comment by Envek** [comment]
I personally like definition blocks more. Especially for long things like descriptions:

```rb
  field :quantity, Integer, null: true do
    preload :variations
    preload_scope ->(*) { VARIATION_RELATION }

    description "Virtual field. Sum of all variations' quantities"
  end
```

But if 1.8 is going in that direction, okay, let it be so. README should be updated then.

I tried your PR and it didn't worked with examples from README (which use definition blocks) and your PR doesn't change README and because of this I decided that your PR doesn't working.

**Comment by CyborgMaster** [comment]
Yeah, sorry, I didn't bother with the README.  That should be done.
Jeremy

**Comment by Envek** [comment]
But I'm wondering that for the sake of backward compatibility it's better to leave methods for definition blocks. Maybe with deprecation warnings though. :thinking:

**Comment by CyborgMaster** [comment]
Although, in 1.8, the block methods are still available, they are deprecated and we have seen problems when using them.  I would like to encourage people to use the new stuff.  Does the gem author have an opinion?

**Comment by RoryO** [comment]
Hello, I'm unsure of the status of this PR. It looks like there is no test infrastructure in place for this library. That makes me nervous to accept and merge PRs that look like there's significant functionality changes.

**Comment by RoryO** [comment]
@CyborgMaster is this considered finished? Is it backwards compatible? We don't have any tests so I can't answer the second.

Note I know little about GraphQL. The original author left the organization. I was looking at open PRs for the org and noticed this. I don't want this to block people but I also do not have any way of determining risk and safety due to lack of knowledge on my part.

**Comment by CyborgMaster** [comment]
This is considered finished.  We've been using it in production in our API without any bugs for a couple months now (since I created the PR).  It is not backward compatible, but `graphql-ruby` version 1.8 is a very big breaking change anyways (in my opinion it would have been better named 2.0), so I'm not too concerned about that.  If people want to move to 1.8, they are looking for breaking changes anyways.

**Comment by RoryO** [comment]
In that case lets change the gemspec to depend on graphql >= 1.8

**Comment by CyborgMaster** [comment]
Very good point.  Done.

**Comment by bbugh** [comment]
Give me an R!
Give me an O!
Give me another R!
Give me a Y!
Give me another O!

What's that spell?! RORYO

Rory, Rory, he's our man, if he can't do it no one can!

**Comment by RoryO** [comment]
Pushed v2.1

**Pull request merged**
