### PR TITLE
 Adds supports for grapqhl-ruby 1.9 new runtime

### PR DESCRIPTION
**Pull request by knshiro**
> GraphQL-Ruby 1.9.0 includes a new runtime module which you may use for your schema. Eventually, it will become the default.

https://graphql-ruby.org/queries/interpreter.html

Problem is that it doesn't support proc-dependent field features anymore. So this PR creates a Field extension to implement the same feature.
https://graphql-ruby.org/type_definitions/field_extensions.html#modifying-field-configuration

NB: Also adds tests and a travis ci config.

### CODE REVIEW

**Comment by jbeker** [comment]
@knshiro May I ask how well this is working for you? I'd like to use it, but I am afraid this repo isn't really being maintained anymore so it may never get merged.

**Comment by knshiro** [comment]
@jbeker I added tests that I stole from https://github.com/Shopify/graphql-batch/blob/master/test/graphql_test.rb and as you can see here https://travis-ci.org/knshiro/graphql-preload I got all the tests to pass. 
I still can't use it in our project though because we are also using https://github.com/exAspArk/graphql-errors and I could not make it work with preload cf https://travis-ci.org/knshiro/graphql-errors

**Comment by jbeker** [comment]
Thanks for the response @knshiro. I think I will steer clear for now until it gets merged but I don't have high hopes for that.

**Comment by mxdavis** [comment]
I see this is more updated, going to try it:

https://github.com/exAspArk/batch-loader

**Comment by tjsingleton** [comment]
This pull request has been closed because it has not had recent activity.

**Comment by nekogami** [comment]
@tjsingleton pretty sure it was only waiting for validation ? Unless there was an issue that was not solved.

While you are here. could you tell us if this gem is still supposed to be supported ?

**Comment by rkorzeniec** [comment]
A friendly bump on that one, right now this is quite a blocker for me. It seems like the solution in this PR should work, definitely using Field Extensions is the way to go.

**Pull request closed without merging**
